OpenAS2/OpenAs2App

Server/src/org/openas2/processor/receiver/DirectoryPollingModule.java, Server/src/org/openas2/processor/resender/DirectoryResenderModule.java
Replaced forceStop() usage with recoverable error.
DirectoryPollingModule now moves the file to the error directory, if it fails to process, instead of relying on forceStop().
DirectoryResenderModule already had error directory handling, simply removed forceStop().
Relevant ticket: https://sourceforge.net/p/openas2/tickets/15/
=> #15 Provide recoverable solution to invalid file name in "toAny" folder

Server/pom.xml, Server/src/main/java/org/openas2/logging/SentryLogger.java
This change adds basic support for configuring Sentry as error tracker. ([https://sentry.io](https://sentry.io))
Configuration is straightforward, simply add following to config.xml:
```
<logger classname="org.openas2.logging.SentryLogger"
dsn="SENTRY DSN" />
```
=> Add Sentry logger

Server/src/test/java/org/openas2/message/AS2MessageMDNTest.java
As originally coded, this test will only pass with timezone offsets that begin with `+`.
=> Allow negative TZ offsets.

Server/src/main/java/org/openas2/processor/sender/AsynchMDNSenderModule.java
Remove header folding was added as an option in https://github.com/OpenAS2/OpenAs2App/pull/39
This was missed from the Async MDN implementation.
PR adds header folding for async MDNs using the same property: `remove_http_header_folding`
Testing performed with passing through an nginx proxy infront of AS2.
=> Add Remove HTTP Header folding property for Async MDNs

Server/src/main/java/org/openas2/params/RandomParameters.java
This PR allows usage of $rand.shortUUID$ to get new random UUID encoded in Base62. This leads into shortening message IDs and therefore shortening file names and log messages as well.
=> Add short UUID random parameter

Server/src/main/java/org/openas2/processor/receiver/NetModule.java
This commit fixes a bug where a socket stays open if an empty or an invalid request has been received. This is a common situation with various TCP layer health check systems.
=> Close sockets even on empty/invalid HTTP request

Server/src/config/config.xml, Server/src/main/java/org/openas2/cmd/processor/SocketCommandProcessor.java, Server/src/main/java/org/openas2/partner/XMLPartnershipFactory.java, Server/src/main/java/org/openas2/processor/receiver/AS2ReceiverHandler.java, Server/src/main/java/org/openas2/processor/storage/BaseStorageModule.java, Server/src/main/java/org/openas2/util/AS2Util.java, Server/src/main/java/org/openas2/util/Properties.java, Server/src/test/java/org/openas2/app/HealthCheckTest.java, Server/src/test/java/org/openas2/message/AS2MessageMDNTest.java, Server/src/test/java/org/openas2/params/ParameterParserTest.java, Server/src/test/java/org/openas2/support/config/FileMonitorAdapterTest.java, Server/src/test/java/org/openas2/support/config/FileMonitorTest.java, Server/src/test/java/org/openas2/util/XMLUtilTest.java
Provide ability for Message-ID to be encapsulated in angle brackets to conform with RFC4130 spec.
Handle possibility of no angle brackets in returned MDN or angle brackets added to Original-Message-ID when sent one was not encapsulated
=> Message id encapsulation

Server/src/main/java/org/openas2/message/BaseMessage.java
Deserialization resets values to null instead of empty map. Set empty
map when deserializing. Fixes exception:
Exception in thread "DirectoryResenderModule"
java.lang.NullPointerException
at org.openas2.message.BaseMessage.addCustomOuterMimeHeader(BaseMessage.java:89)
at org.openas2.processor.sender.AS2SenderModule.addCustomHeaders(AS2SenderModule.java:461)
at org.openas2.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:92)
at org.openas2.processor.DefaultProcessor.handle(DefaultProcessor.java:65)
at org.openas2.processor.resender.DirectoryResenderModule.processFile(DirectoryResenderModule.java:186)
at org.openas2.processor.resender.DirectoryResenderModule.resend(DirectoryResenderModule.java:106)
at org.openas2.processor.resender.BaseResenderModule$PollTask.run(BaseResenderModu …
=> Fix nullpointer exception when resending message with custom headers.

Server/src/main/java/org/openas2/processor/receiver/NetModule.java
Re-using threads can be a lot more efficient than creating new threads,
especially under heavy load. There is room for further improvement: e.g. set an upper limit to the amount of threads in the pool to prevent an overload, switch to using daemon threads so that the server can always be stopped after a timeout.
=> Use a threadpool to handle incoming connections.

Server/src/main/java/org/openas2/partner/Partnership.java, Server/src/main/java/org/openas2/processor/receiver/NetModule.java, Server/src/main/java/org/openas2/processor/sender/AS2SenderModule.java, Server/src/main/java/org/openas2/processor/sender/MDNSenderModule.java, Server/src/main/java/org/openas2/util/HTTPUtil.java, Server/src/test/resources/OpenAS2ServerTest/OpenAS2B/config/partnerships.xml
Added partnership option no_chunked_max_size that, when set to a
positive number, will set a "Content-Length" header in the HTTP POST
message transfers and disables chunked transfer coding.
This option should not be needed in production, but can help with testing when faced with other AS2 servers that do not support chunked transfers. To make this a production feature, the implementation should use a temporary file to determine size (Content-Length) and stream from the temporary file to prevent abnormal memory usage.
=> Option to disable chunking for specific partners.

Server/src/main/java/org/openas2/util/HTTPUtil.java
The default pooling connection manager adds setup costs for creating a
HTTP Client that is only used for one request. The basic connection
manager only handles one connection and reduces setup costs.
Also improve request configuration building - proxy-configuration no
longer overwrites "options" (connection timeouts) configuration.
=> Use a basic connection manager for the HTTP Client.

Server/src/main/java/org/openas2/lib/helper/BCCryptoHelper.java, Server/src/main/java/org/openas2/util/AS2Util.java, Server/src/test/resources/OpenAS2ServerTest/OpenAS2A/config/partnerships.xml, Server/src/test/resources/OpenAS2ServerTest/OpenAS2B/config/partnerships.xml
The option "rename_digest_to_old_name" has generic support in
BouncyCastle, so use that. Solution similar to:
https://github.com/phax/as2-lib/commit/ed08dd00b6d721ec3e3e7255f642045c9cbee9c3
Fix a couple of unhelpful NullPointerExceptions and remove 2 partnership
options that no longer exist.
=> Use a more generic solution for compatability with micalg values.

Server/src/bin/start-openas2.bat, Server/src/bin/start-openas2.sh
Starting OpenAS2 with openas2.service fails when the PID-file location
is changed because the start-script does not use the OPENAS2_PID
variable set by the service. The start-script used PID_FILE.
Also tweak the start-script example with EXTRA_PARMS for using old
certificates ("org.bouncycastle.asn1.allow_unsafe_integer").
=> Systemd service uses OPENAS2_PID, startup script must use that too.

Server/src/main/java/org/openas2/processor/storage/BaseStorageModule.java, Server/src/main/java/org/openas2/util/AS2Util.java, Server/src/main/java/org/openas2/util/IOUtil.java
The move-file method did a lot of file operations that could mostly be
skipped on the "happy path". In some cases an atomic move is required
(e.g. moving a file to an inbox), debug logging will now show the
move-operation. Also made the "create directories" call synchronized to
prevent any race-conditions and log which directories are created.
Removed some pre Java 7 code in the file-delete method that is no longer
needed.
=> Optimize move-file method to use atomic move.

Server/src/main/java/org/openas2/cmd/processor/RestCommandProcessor.java
Registering JacksonFeature fixes #177 where the REST API returned status code 500 because it did not find a MessageBodyWriter for application/json.
=> Registering JacksonFeature to fix error with JSON response

Server/src/main/java/org/openas2/processor/receiver/AS2ReceiverHandler.java
If a monitoring system invokes the health check each 30s, OpenAS will
generate useless 5760 log entries. Those log entries are noise can
can overwhelm the log analytics systems. The log level for those
two entries has been decreased to DEBUG. Logging for the real data
transfers as well as for the errors still present.
=> Decreased noise in logs

Dockerfile, start-container.sh
Dockerfile:
1. Removed the trailing / in the environment variables. Doing this made the rest of the file look more readable. Dockerfile also accepts variable references in the form ${variable}. This helps when joining variables and strings.
2. Added the destination directories to the COPY commands. All the files were being dumped into the $OPENAS2_HOME directory.
3. Created config directory
start-container.sh:
1. Removed 'cd' command. There is no config_template directory inside the config_template directory.
I would also like to point out that if $OPENAS2_BASE and $OPENAS2_HOME are different, start-container.sh will fail to copy the files and OpenAS2 will complain about no config.xml.
#226
=> Update Dockerfile and start-container.sh

WebUI/package.json
no-console rule is needed to avoid getting errors on build when console.log is found within the src.
=> Add no-console rule to WebUI

Server/src/main/java/org/openas2/util/AS2Util.java
Not sure if opening a PR like this is helpful, but this is the change I needed to make to resolve an issue I was having with synchronous MDN processing.  It appears to be similar to code changes I looked at:
here: https://github.com/OpenAS2/OpenAs2App/pull/93 
and here: https://github.com/OpenAS2/OpenAs2App/pull/92
I was getting a PartnershipNotFound exception when processing an MDN response for a partner who is using a space in their AS2 identifier.  
This change seems to fix the issue.  With some guidance I'm willing to write some tests/clean this up if we think this is something worth pulling into the main project.
=> Remove double quotes from as2id on sync mdns

Server/src/main/java/org/openas2/util/HTTPUtil.java
Curious if this makes sense to others as I think it makes sense for my team.  This exception happens when someone just opens the as2 url in a browser (happens a lot during setups). The exception causes more log/alerting noise than we desire as we monitor for exceptions being logged pretty closely.  It appears that we're already returning enough information for the user to know what the issue is, and there is also information being logged besides the exception details.
=> Avoid IOException when missing Content-Length

Server/src/main/java/org/openas2/cmd/processor/RestCommandProcessor.java
It looks like that this PR https://github.com/OpenAS2/OpenAs2App/pull/270 broke the JSON encoding. This broke the WebUI. I readded `JacksonFeature.class`, assuming it was removed unintentionally. 
Before:
With the fix in this PR:
=> Fix: JacksonFeature not registered

Server/src/bin/start-openas2.bat
The `set` command was missing before the CLASSPATH so that it generated a "command not found" message.
=> set CLASSPATH in start-openas2.bat

Server/src/bin/import_public_cert.bat
The angle brackets were not escaped in the usage message. So the batch script stopped with an error message when it should display the usage message.
Also the batch filename will be used in the usage message (that is the ``%~nx0``).
=> Update usage message in import_public_cert.bat

Server/src/main/java/org/openas2/cmd/processor/RestCommandProcessor.java
RestCommandProcessor.processCommand() did nothing and BaseCommandProcessor.schedule called processCommand in an endless loop, resulting in a thread which continuously processed an endless loop.
By overriding schedule there is no loop any more.
Closes #283.
=> Fix high cpu consumption in RestCommandProcessor

Dockerfile_WebUI, README.md, Server/src/config/config.xml, WebUI/package.json, WebUI/src/components/LoginScreen.vue, WebUI/src/main.js, WebUI/src/models/Partner.js, WebUI/yarn.lock
The WebUI does not build correctly without some fixes. This PR fixes those issues and allows you to run the WebUI out of the box.
- Pinned the node.js to version 16 in Dockerfile_WebUI, since the libraries used do not support newer versions of node.js
- Cleaned up docker instructions in README.md, and added instructions for Dockerfile_WebUI
- Enabled the REST API by default, so that it's easier to use the WebUI
- Removed references to vuetify, since vuetify was removed in f2740226
- Fixed eslint parser configuration. This was previously causing errors during the build process
- Set the WebUI login server to "http" by default, instead of "https"
- Updated yarn.lock with the dependency changes
=> Fix various issues with the WebUI

Server/src/main/java/org/openas2/processor/sender/AS2SenderModule.java
Logging shows: `Message sent and response received in 2804 millisecondsms`.
This commit removes the duplicate "ms" part.
=> "ms" removed from logging of transfer time

Server/src/main/java/org/openas2/XMLSession.java, changes.txt
While reading the code and trying to figure out how it all worked, I noticed this typo.
=> Fix typo 'confog' to 'config'

.gitattributes
On Windows by default Git changes line endings locally to CR LF which makes scripts like mvnw fail when copied into the comntainer, see also: https://github.com/OpenAS2/OpenAs2App/issues/303
This settings forces Git to keep the LF line ending locally.
=> Set line endings to LF

RELEASE-NOTES.md, Remote/pom.xml, Server/pom.xml, Server/src/main/java/org/openas2/processor/resender/DirectoryResenderModule.java, changes.txt, pom.xml
If all resend attemots fail, the message was deleted instead of being saved to the errordir.
=> Fix resend failure to persist to errordir

README.md, docker-compose.yml
Since the default listening port for the REST processor has been changed to 8080, so should the ports bindings of docker commands. I kept the host port to 8443 to prevent conflicts with the UI port also being in 8080.
I also added a note for the server field to prevent questions about not responding from remote.
Finally I added volume bindings for data and config folder, for easier configuration of docker images.
=> Fix Ports and add volume bindings for Docker

Dockerfile, Dockerfile_WebUI
The used openjdk:11 package in the Dockerfile was last built 2 years ago and contains several vulnerabilities (see https://hub.docker.com/layers/library/openjdk/11-jre-slim/images/sha256-884c08d0f406a81ae1b5786932abaf399c335b997da7eea6a30cc51529220b66?context=explore).
Thus I have used eclipse-temurin:11.0.22_7-jre-jammy as a base which is actively supported.
I also switched to nginx_stable-alpine  for the WebUI dockerfile as it is smaller.
=> Updating Dockerfile to more recent base images

Server/src/main/java/org/openas2/message/BaseMessage.java, Server/src/main/java/org/openas2/message/Message.java, Server/src/main/java/org/openas2/processor/Processor.java, Server/src/main/java/org/openas2/processor/receiver/DirectoryPollingModule.java, Server/src/main/java/org/openas2/processor/receiver/MessageBuilderModule.java, Server/src/main/java/org/openas2/processor/resender/DirectoryResenderModule.java, Server/src/main/java/org/openas2/processor/sender/AS2SenderModule.java, Server/src/main/java/org/openas2/util/AS2Util.java
Prevent call to file cleanup when message goes into resend queue by providing and explicit bollena that is set by the reender module on the Message object.
=> Resend file cleanup error

Server/src/main/java/org/openas2/util/HTTPUtil.java
Description
This pull request introduces an enhancement to HTTPUtil.java in OpenAS2 to improve handling of self-signed certificates. Previously, the only option for trusting self-signed certificates was the TrustSelfSignedCN system property, which is not ideal in most cases.
Problem Statement
In our setup, we must accept self-signed certificates from trading partners when sending messages to them. Additionally, in a Kubernetes environment, relying on system properties is cumbersome and inflexible. Configuring trusted self-signed certificates with TrustSelfSignedCN would require a Docker image rebuild whenever certificates change, limiting the ability to update certificates independently of the application image.
Solution
This update allows OpenAS2 to dynamically load trusted self-signed …
=> Improvement: Additional way to handle self-signed certificates if necessary

WebUI/package.json, WebUI/yarn.lock, docker-compose.yml
Have reverted the vue update - vue3 is different from vue2 and there are breaking changes. To "stabilize" the current version (UI is not changed to vue3 yet) I have reverted back. 
Also, it seems the environment variables had quotes and typo, which prevents them from being populated correctly. Also the RESTAPI was not enabled, which led to https://github.com/OpenAS2/OpenAs2App/issues/320 as well - believe this is not necessary. 
This should also fix #399 and #400
=> Bugfix/revert vue version - fix docker-compose

RELEASE-NOTES.md, Server/pom.xml, Server/src/main/java/org/openas2/util/AS2Util.java, changes.txt, pom.xml
Fix incorrectly cleaning up files when resend mode is entered.
=> Pending mdn file handling on resend

RELEASE-NOTES.md, Server/pom.xml, Server/src/main/java/org/openas2/processor/receiver/DirectoryPollingModule.java, changes.txt, pom.xml
Add a concurrent access safe list to track processed files and remove them as part of the update_tracking method flow.
=> Fix concurrent processing error
