- Server/src/org/openas2/processor/receiver/DirectoryPollingModule.java
- Server/src/org/openas2/processor/resender/DirectoryResenderModule.java
> Revert "#15 Provide recoverable solution to invalid file name in "toAny" folder"

- Server/src/main/java/org/openas2/processor/receiver/AS2MDNReceiverHandler.java
- Server/src/main/java/org/openas2/processor/receiver/AS2ReceiverHandler.java
- Server/src/main/java/org/openas2/processor/receiver/MessageBuilderModule.java
Fix missing DIRECTION and FILE_NAME fields when logging message state to the database
> State processing value fixes

- Server/src/main/java/org/openas2/logging/LogManager.java
- Added default logger for cases when no logger are configured.
- Refactored initialization of LogManager
> Refined LogManager

- Server/src/main/java/org/openas2/message/BaseMessage.java
- Server/src/main/java/org/openas2/processor/receiver/AS2ReceiverHandler.java
Try to support reverse proxies by reading X-Real-IP and X-Forwarded-For
HTTP headers.
> Support reverse proxies (based on dev branch)

- Server/src/bin/openas2.service
OpenAS2 server returns RC 143 on successful shutdown and systemd should expect so.
> Fix expected service RC

- Server/src/main/java/org/openas2/OpenAS2Exception.java
- Server/src/main/java/org/openas2/app/OpenAS2Server.java
- Server/src/main/java/org/openas2/lib/helper/ICryptoHelper.java
Following our exchanges I will take the time to do push step by step.
- JCE error handling (Java Cryptography Extension)
- Invalid code in OpenAS2Exception
> Stepbystep

- RELEASE-NOTES.md
- Server/src/main/java/org/openas2/processor/resender/DirectoryResenderModule.java
- Server/src/main/java/org/openas2/processor/sender/AS2SenderModule.java
- Server/src/main/java/org/openas2/processor/sender/MDNSenderModule.java
- Server/src/main/java/org/openas2/schedule/SchedulerComponent.java
- Server/src/main/java/org/openas2/util/AS2Util.java
- Server/src/main/java/org/openas2/util/Properties.java
If a message is sent requesting an ASYNC MDN and the partner does not respond with an MDN then the sent file remains pending. This fix will cater for this situation.
> Async mdn no response fix

- Server/src/main/java/org/openas2/lib/helper/BCCryptoHelper.java
The trace logging of a signature does no null-checks on data to show in
logging. This can result in a NPE that fails the entire MDN.
> Fix NPE in trace logging of signature.

- Server/src/main/java/org/openas2/logging/FileLogger.java
Log file can be truncated if writes are not synchronized.
> Synchronize writes to log-file.

- Server/src/config/config.xml
- Server/src/main/java/org/openas2/processor/receiver/AS2ReceiverHandler.java
- Server/src/main/java/org/openas2/util/XMLUtil.java
- Server/src/test/java/org/openas2/app/AttributeEnhancerTest.java
Provide ability to use the attribute enhancer feature in all components to simplify configuration strings and config changes.
> Attribute enhancer support for all components

- Server/src/main/java/org/openas2/processor/sender/AS2SenderModule.java
- Server/src/main/java/org/openas2/util/AS2Util.java
Change log messages to get better reporting of the error.
Fix some log message spelling errors
> Change logging for file cleanup method

- Bundle/pom.xml
- RELEASE-NOTES.md
- Remote/pom.xml
- Server/pom.xml
- Server/src/main/java/org/openas2/XMLSession.java
- changes.txt
- pom.xml
1. Modify the way the application identifies the correct manifest file to determine title and version of the app.
2. Alter the file cleanup logging messages to make it easier to debig issues.
3. Correct minor spelling errors in logging statements
> Enhance manifest lookup

- Server/src/config/config.xml
Fix the sample sentdir and errordir for DirectoryPollingModule in config.xml
> Fix error configuring sample DirectoryPollingModule attribs

- Bundle/pom.xml
- RELEASE-NOTES.md
- Remote/pom.xml
- Server/pom.xml
- Server/src/main/java/org/openas2/util/AS2Util.java
- changes.txt
- pom.xml
Invoke file name cleaner on sent/error files
> Clean sent filename

- Server/src/main/java/org/openas2/BaseSession.java
- Server/src/main/java/org/openas2/app/OpenAS2Server.java
Changes to simplify creating plugins for OpenAS2.
Making Session and Server more extensible.
After the discussion on the PR: CodeRefactor, I decided there was no good enough reason to introduce the refactoring changes, therefore I drop them in favor for minimal needed code changes.
> Minor Method access for plugins

- Server/src/main/java/org/openas2/processor/msgtracking/DbTrackingModule.java
... of param definition PARAM_FORCE_LOAD_JDBC_DRIVER
> fixed wrong parameter mapping

- Server/src/main/java/org/openas2/processor/receiver/AS2ReceiverHandler.java
- Server/src/main/java/org/openas2/util/Properties.java
> Allow control over the case when an invalid message is received by the

- Server/src/main/java/org/openas2/util/AS2Util.java
> Handle InputStream when reading MDN text

- Server/src/main/java/org/openas2/util/HTTPUtil.java
Currently, the `http.nonProxyHosts` property is ignored when determining if a proxy should be used.
This PR adds this, although using the `DefaultProxySelector` for the whole proxy logic would probably be better. I did it that way in order to touch as little as possible of the existing code.
> Honour http.nonProxyHosts property

- RELEASE-NOTES.md
- Server/src/config/config.xml
- Server/src/main/java/org/openas2/BaseSession.java
- Server/src/main/java/org/openas2/Session.java
- Server/src/main/java/org/openas2/XMLSession.java
- Server/src/main/java/org/openas2/partner/XMLPartnershipFactory.java
- Server/src/main/java/org/openas2/processor/receiver/DirectoryPollingModule.java
- Server/src/main/java/org/openas2/processor/receiver/PollingModule.java
- changes.txt
Fix the refresh or partnerships stpping the pollers that are configured in the config.xml
> Prevent non partnership pollers being refreshed

- README.md
- docker-compose.yml
Extends the Docker instructions to include Docker Compose.
> Added Docker compose and updated README with instructions

- RELEASE-NOTES.md
- Remote/pom.xml
- Server/pom.xml
- Server/src/main/java/org/openas2/lib/helper/BCCryptoHelper.java
- changes.txt
- pom.xml
Translate Elliptic Curve identifier extracted from certificate to be compatible with BouncyCastle library.
> Support ECDSA encryption

- Server/src/main/java/org/openas2/processor/msgtracking/EmbeddedDBHandler.java
Log JDBC driver name on server startup
> Log JDBC driver name on server startup

- WebUI/public/index.html
> Update CDN links with latest and add integrity check to remove CodeQL

- Server/src/main/java/org/openas2/processor/receiver/AS2ReceiverHandler.java
regardless of property use_old_mime_deserialise_method
> Set header value for Content-Transfer-Encoding for every request

- RELEASE-NOTES.md
- Server/pom.xml
- changes.txt
- pom.xml
> New release with minor enhancement to support AS2 systems that are not strictly specification compliant.
